FROM thebloke/ubuntu2204-cuda118-pytorch2
ENV PIP_DEFAULT_TIMEOUT=10000 
COPY ./requirements.txt requirements.txt
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y openssh-client git curl && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install -y git-lfs
RUN pip install --no-cache-dir -r requirements-train.txt
WORKDIR /workspace
COPY peft peft
COPY finetune finetune
COPY utils utils
RUN cd peft && pip install -e . && cd ..
RUN export GIT_LFS_SKIP_SMUDGE=0
RUN git clone https://huggingface.co/Qwen/Qwen-14B Qwen/Qwen-14B
CMD ["bash", "finetune.sh"]